<a href="https://colab.research.google.com/github/yvessong23/ML-TEAM-15/blob/main/Copy_of_BinBuddiesCNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import TensorFlow
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score, f1_score, roc_auc_score
import seaborn as sns

In [ ]:
%pip install numpy
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import hashlib, os
from PIL import Image
%pip install kagglehub
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import kagglehub

# Download latest version
path = kagglehub.dataset_download("zlatan599/garbage-dataset-classification")
rgb_path = "cleaned/garbage-dataset-rgb"
print("Path to dataset files:", path)

hashes = {}
duplicates = []

def file_hash(filePath):
    with open(filePath, "rb") as f: # Open and read files for hashing
        file_bytes = f.read()
        return hashlib.md5(file_bytes).hexdigest()

for root, dirs, files in os.walk(path):
    for file in files:
        file_path = os.path.join(root, file)
        h = file_hash(file_path)

        if h in hashes:
            print(f"Duplicate found! Removing {file_path} (same as {hashes[h]})")
            try:
                os.remove(file_path)
                duplicates.append((file_path, hashes[h]))
            except OSError as e:
                print(f"Warning: Could not remove {file_path} due to read-only filesystem. Error: {e}")
        else:
            hashes[h] = file_path
            try:
                # Preserve the dataset’s subfolder structure
                rel_dir = os.path.relpath(root, path)
                save_dir = os.path.join(rgb_path, rel_dir)
                os.makedirs(save_dir, exist_ok=True)

                save_path = os.path.join(save_dir, file)

                # Skip non-image files (like metadata.csv)
                if not file.lower().endswith((".jpg", ".jpeg", ".png", ".bmp", ".tiff")):
                    continue

                with Image.open(file_path) as img:
                    img.convert("RGB").save(save_path)

            except Exception as e:
                print(f"Error processing {file_path}: {e}")

100%|██████████| 121M/121M [00:04<00:00, 26.3MB/s]

Extracting files...


Path to dataset files: /root/.cache/kagglehub/datasets/zlatan599/garbage-dataset-classification/versions/5
Duplicate found! Removing /root/.cache/kagglehub/datasets/zlatan599/garbage-dataset-classification/versions/5/Garbage_Dataset_Classification/images/plastic/plastic_00074.jpg (same as /root/.cache/kagglehub/datasets/zlatan599/garbage-dataset-classification/versions/5/Garbage_Dataset_Classification/images/plastic/plastic_02280.jpg)
Duplicate found! Removing /root/.cache/kagglehub/datasets/zlatan599/garbage-dataset-classification/versions/5/Garbage_Dataset_Classification/images/plastic/plastic_02209.jpg (same as /root/.cache/kagglehub/datasets/zlatan599/garbage-dataset-classification/versions/5/Garbage_Dataset_Classification/images/plastic/plastic_00861.jpg)
Duplicate found! Removing /root/.cache/kagglehub/datasets/zlatan599/garbage-dataset-classification/versions/5/Garbage_Dataset_Classification/images/plastic/plastic_01905.jpg (same as /root/.cache/kagglehub/datasets/zlatan599/garb

In [ ]:
import os
import numpy as np
import pandas as pd
from PIL import Image

from sklearn.model_selection import train_test_split

from tensorflow.keras import models, layers, regularizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.optimizers import Adam

rgb_path = "cleaned/garbage-dataset-rgb"
base_path = os.path.join(rgb_path, "Garbage_Dataset_Classification", "images")
DATASET_DIR = base_path

# Set up class names
class_names = ['cardboard', 'glass', 'metal', 'paper', 'plastic', 'trash']
num_classes = len(class_names)

# Ensure 'duplicates' is defined. It is expected to be populated by cell WJM9MyG1JvjH.
# If cell WJM9MyG1JvjH hasn't been run, 'duplicates' will be an empty list, and thus
# no files will be filtered as duplicates in this cell.
if 'duplicates' not in globals():
    duplicates = []

# Verify and collect all image paths and their labels
image_paths = []
labels = []

duplicate_filepaths = {f[0] for f in duplicates} # Extract only the file paths from the duplicates list

for class_idx, class_name in enumerate(class_names):
    class_dir = os.path.join(base_path, class_name)
    if os.path.exists(class_dir):
        class_images = [f for f in os.listdir(class_dir)
                       if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff'))]
        print(f"{class_name}: {len(class_images)} images")

        for img_file in class_images:
            full_path = os.path.join(class_dir, img_file)
            if full_path not in duplicate_filepaths: # Only add if not a duplicate
                image_paths.append(full_path)
                labels.append(class_idx)
    else:
        print(f"Warning: {class_dir} does not exist")

cardboard: 1718 images
glass: 2292 images
metal: 1628 images
paper: 1809 images
plastic: 1710 images
trash: 2500 images


In [ ]:
from tensorflow.keras import models, layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

from sklearn.model_selection import train_test_split
import numpy as np

IMG_HEIGHT = 256
IMG_WIDTH = 256
IMG_SIZE   = (IMG_HEIGHT, IMG_WIDTH)
BATCH_SIZE = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.3
)

val_test_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    DATASET_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training',
    shuffle=True,
    seed=42
)

# Load all validation images into memory, then split into val + test
val_generator_full = val_test_datagen.flow_from_directory(
    DATASET_DIR,
    target_size=IMG_SIZE,
    batch_size=1,
    class_mode='categorical',
    subset='validation',
    shuffle=False,
    seed=42
)

val_data = []
val_labels = []

for i in range(len(val_generator_full)):
    x, y = val_generator_full[i]
    val_data.append(x[0])
    val_labels.append(y[0])

val_data = np.array(val_data)
val_labels = np.array(val_labels)

X_val, X_test, y_val, y_test = train_test_split(
    val_data,
    val_labels,
    test_size=0.5,
    random_state=42,
    stratify=np.argmax(val_labels, axis=1)
)

val_generator_data = (X_val, y_val)
test_generator_data = (X_test, y_test)

model_gap = models.Sequential([
    layers.Input(shape=(IMG_HEIGHT, IMG_WIDTH, 3)),

    # Block 1
    layers.Conv2D(32, (3,3), padding='same', activation='relu'),
    layers.Conv2D(64, (3,3), padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPool2D(2),

    # Block 2
    layers.Conv2D(128, (5,5), padding='same', activation='relu'),
    layers.BatchNormalization(),
    layers.MaxPool2D(2),

    # Block 3
    layers.Conv2D(256, (3,3), padding='same', activation='relu',
                  kernel_regularizer=regularizers.l2(0.01)),
    layers.BatchNormalization(),
    layers.MaxPool2D(2),

    # Block 4
   layers.Conv2D(512, (3,3), padding='same', activation='relu',
                  kernel_regularizer=regularizers.l2(0.01)),
    layers.BatchNormalization(),
    layers.MaxPool2D(2),

    # Head with GAP
    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
    layers.BatchNormalization(),
    layers.Dense(6, activation='softmax'),
])


# model_flatten = models.Sequential([
#     layers.Input(shape=(IMG_HEIGHT, IMG_WIDTH, 3)),

#     # Block 1
#     # Block 1
#     layers.Conv2D(32, (3,3), padding='same', activation='relu'),
#     layers.Conv2D(64, (3,3), padding='same', activation='relu'),
#     layers.BatchNormalization(),
#     layers.MaxPool2D(2),

#     # Block 2
#     layers.Conv2D(128, (5,5), padding='same', activation='relu'),
#     layers.BatchNormalization(),
#     layers.MaxPool2D(2),

#     # Block 3
#     layers.Conv2D(256, (3,3), padding='same', activation='relu',
#                   kernel_regularizer=regularizers.l2(0.01)),
#     layers.BatchNormalization(),
#     layers.MaxPool2D(2),

#     # Block 4
#    layers.Conv2D(512, (3,3), padding='same', activation='relu',
#                   kernel_regularizer=regularizers.l2(0.01)),
#     layers.BatchNormalization(),
#     layers.MaxPool2D(2),

#     # Flatten Head
#     layers.Flatten(),
#     layers.Dense(256, activation='relu', kernel_regularizer=regularizers.l2(0.01)),
#     layers.BatchNormalization(),
#     layers.Dense(6, activation='softmax'),
# ])

Found 8162 images belonging to 6 classes.
Found 2329 images belonging to 6 classes.


# Testing CNN model with Flattening

https://www.kaggle.com/code/ahmadjaved097/multiclass-image-classification-using-cnn

Flatten is used in CNNs to transition convolutional feature maps to fully connected layers. Flatten simpler unrolls all the values in the feature maps into a single vector. This can result in a large number of parameters. 5+ million in this case.

* Time:
* Val Acc:
* Val Loss:
* Train Acc:
* Train Loss:

In [ ]:
# print(tf.config.list_physical_devices("GPU"))

# early_stopping = EarlyStopping(
#     monitor='val_loss',
#     patience=5,
#     restore_best_weights=True
# )

# checkpoint = ModelCheckpoint(
#     'best_model_flatten.keras',
#     monitor='val_loss',
#     save_best_only=True,
#     mode='min',
#     verbose=1
# )
# model_flatten.compile(
#     optimizer=Adam(learning_rate=1e-3),
#     loss='categorical_crossentropy',
#     metrics=['accuracy']
# )

# model_flatten.summary()

# history = model_flatten.fit(
#     train_generator,
#     validation_data=val_generator_data,
#     epochs=30,
#     callbacks=[early_stopping, checkpoint]
# )

# test_loss, test_acc = model_flatten.evaluate(X_test,
#     y_test,
#     batch_size=BATCH_SIZE,
#     verbose=2
# )

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_5 (Conv2D)               │ (None, 256, 256, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 256, 256, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_5           │ (None, 256, 256, 64)   │           256 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 128, 128, 64)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 128, 128, 128)  │       204,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_6           │ (None, 128, 128, 128)  │           512 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_5 (MaxPooling2D)  │ (None, 64, 64, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_8 (Conv2D)               │ (None, 64, 64, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_7           │ (None, 64, 64, 256)    │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_6 (MaxPooling2D)  │ (None, 32, 32, 256)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_9 (Conv2D)               │ (None, 32, 32, 512)    │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_8           │ (None, 32, 32, 512)    │         2,048 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_7 (MaxPooling2D)  │ (None, 16, 16, 512)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 131072)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 256)            │    33,554,688 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_9           │ (None, 256)            │         1,024 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 6)              │         1,542 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 35,260,742 (134.51 MB)

 Trainable params: 35,258,310 (134.50 MB)

 Non-trainable params: 2,432 (9.50 KB)

Epoch 1/30


/usr/local/lib/python3.12/dist-packages/keras/src/trainers/data_adapters/py_dataset_adapter.py:121: UserWarning: Your `PyDataset` class should call `super().__init__(**kwargs)` in its constructor. `**kwargs` can include `workers`, `use_multiprocessing`, `max_queue_size`. Do not pass these arguments to `fit()`, as they will be ignored.
  self._warn_if_super_not_called()


256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 354ms/step - accuracy: 0.4294 - loss: 11.3752
Epoch 1: val_loss improved from inf to 3.56090, saving model to best_model_flatten.keras
256/256 ━━━━━━━━━━━━━━━━━━━━ 156s 445ms/step - accuracy: 0.4295 - loss: 11.3583 - val_accuracy: 0.1589 - val_loss: 3.5609
Epoch 2/30
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step - accuracy: 0.4778 - loss: 2.5625
Epoch 2: val_loss improved from 3.56090 to 2.64835, saving model to best_model_flatten.keras
256/256 ━━━━━━━━━━━━━━━━━━━━ 92s 360ms/step - accuracy: 0.4778 - loss: 2.5620 - val_accuracy: 0.3247 - val_loss: 2.6484
Epoch 3/30
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 321ms/step - accuracy: 0.4917 - loss: 2.2145
Epoch 3: val_loss did not improve from 2.64835
256/256 ━━━━━━━━━━━━━━━━━━━━ 85s 331ms/step - accuracy: 0.4917 - loss: 2.2149 - val_accuracy: 0.2543 - val_loss: 8.9101
Epoch 4/30
256/256 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step - accuracy: 0.4707 - loss: 3.2848
Epoch 4: val_loss improved from 2.64835 to 2.46293, saving model to

# Testing CNN with Global Average Pooling

Using ChatGPT and Kaggle, I found that GAP or Global Average Pooling can significantly reduce the number of parameters. This method compresses each feature map into a single value by averaging its activations (outputs). This reduced our dimensionality from 5+ million to about 56K. This also allows the model to generalize better and train faster.
https://www.kaggle.com/code/faressayah/cifar-10-images-classification-using-cnns-88
https://www.kaggle.com/code/zlatan599/f1-0-97-garbage-classif-final-version-2

The baseline run of this model with no dropout, data augmentation, or hyperparameter tuning was:

* Time:
* Val Acc:
* Val Loss:
* Train Acc:
* Train Loss:

In [ ]:
# print(tf.config.list_physical_devices("GPU"))

# model_gap.compile(
#     optimizer=Adam(learning_rate=1e-3),
#     loss='categorical_crossentropy',
#     metrics=['accuracy'],
# )

# model_gap.summary()


# early_stopping = EarlyStopping(
#     monitor='val_loss',
#     patience=5,
#     restore_best_weights=True
# )

# checkpoint = ModelCheckpoint(
#     'best_model_gap.keras',
#     monitor='val_loss',
#     save_best_only=True,
#     mode='min',
#     verbose=1
# )

# history_gap = model_gap.fit(
#     train_generator,
#     validation_data=val_generator_data,
#     epochs=30,
#     callbacks=[early_stopping, checkpoint]
# )

# test_loss, test_acc = model_gap.evaluate(
#     X_test,
#     y_test,
#     batch_size=BATCH_SIZE,
#     verbose=2
# )

Model Evaluation at baseline


---

Comparing GAP vs Flatten Head

In [ ]:
test_images, test_labels = test_generator_data

y_probs = model_gap.predict(test_images)

y_pred = np.argmax(y_probs, axis=1)
y_true = np.argmax(test_labels, axis=1)

print("\nClassification Report:")
print(classification_report(y_true, y_pred, target_names=class_names))

precision_macro = precision_score(y_true, y_pred, average='macro')
recall_macro = recall_score(y_true, y_pred, average='macro')
f1_macro = f1_score(y_true, y_pred, average='macro')

precision_weighted = precision_score(y_true, y_pred, average='weighted')
recall_weighted = recall_score(y_true, y_pred, average='weighted')
f1_weighted = f1_score(y_true, y_pred, average='weighted')

In [ ]:
# test_images, test_labels = test_generator_data

# y_probs = model_flatten.predict(test_images)

# y_pred = np.argmax(y_probs, axis=1)
# y_true = np.argmax(test_labels, axis=1)

# cm = confusion_matrix(y_true, y_pred)
# print("Confusion Matrix:\n", cm)

# print("\nClassification Report:")
# print(classification_report(y_true, y_pred, target_names=class_names))

# precision_macro = precision_score(y_true, y_pred, average='macro')
# recall_macro = recall_score(y_true, y_pred, average='macro')
# f1_macro = f1_score(y_true, y_pred, average='macro')

# precision_weighted = precision_score(y_true, y_pred, average='weighted')
# recall_weighted = recall_score(y_true, y_pred, average='weighted')
# f1_weighted = f1_score(y_true, y_pred, average='weighted')

37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 89ms/step
Confusion Matrix:
 [[151   8   4   3   0   6]
 [ 26  88  12  48   7  48]
 [ 23  22  51  19   4  43]
 [ 36   4  64  48   4  25]
 [ 14  34  18  27  34  44]
 [ 24  24  56  24   7 115]]

Classification Report:
              precision    recall  f1-score   support

   cardboard       0.55      0.88      0.68       172
       glass       0.49      0.38      0.43       229
       metal       0.25      0.31      0.28       162
       paper       0.28      0.27      0.27       181
     plastic       0.61      0.20      0.30       171
       trash       0.41      0.46      0.43       250

    accuracy                           0.42      1165
   macro avg       0.43      0.42      0.40      1165
weighted avg       0.43      0.42      0.40      1165

